
<?php 
header('Content-type: application/xml; charset="ISO-8859-1"',true);  
	$TotalSearchPage = 1;
	if($API_LastUpdateManga->API_MangaRs->Status == "Not Complete"){ 
	}else{
		$TotalSearchPage =$API_LastUpdateManga->API_MangaRs->Body->TotalSearchPage;
	}
?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>	
		<loc><?php echo base_url().'sitemap/manga/list-manga-0.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php foreach (range('A', 'Z') as $char) { ?>
	<sitemap>	
		<loc><?php echo base_url().'sitemap/manga/list-manga-'.$char.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php } ?>

<?php for($i = 1 ; $i <= $TotalSearchPage ;$i++) {?>
	<sitemap>	
		<loc><?php echo base_url().'sitemap/manga/manga-pages-'.$i.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php } ?>
</sitemapindex>

<!-- XML Sitemap generated by Yoast SEO -->
