
<?php 
header('Content-type: application/xml; charset="ISO-8859-1"',true);  
{// last update
  $TotalSearchPageHome = 0;
  if($API_LastUpdate->API_TheMovieRs->Status == "Not Complete"){ 
  }else{
    $TotalSearchPageHome = $API_LastUpdate->API_TheMovieRs->Body->TotalSearchPage;
  }
}
?>

<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" 
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" 
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?php if($API_LastUpdate->API_TheMovieRs->Status == "Not Complete"){ ?>
        <url>	
            <loc><?php echo base_url();?></loc>
            <lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
        </url>
    <?php }else{?>
        <url>	
            <loc><?php echo base_url();?></loc>
            <lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
        </url>
        <?php foreach($API_LastUpdate->API_TheMovieRs->Body->LastUpdateAnime as $API_TheMovieRS){ ?>
            <?php //$slug = $API_TheMovieRS->IdListEpisode.'-'.$API_TheMovieRS->SlugEp; ?>
            <?php $slug = $API_TheMovieRS->SlugEp; ?>
            <?php $publishDate = $API_TheMovieRS->PublishDate; ?>
            <url>
                <loc><?php echo site_url('streaming/'.$slug); ?></loc>
                <lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
            </url>
        <?php } ?>
    <?php } ?>
</urlset>
<!-- </xml> -->
<!-- XML Sitemap generated by Yoast SEO -->
