
<?php 
$TotalSearchPage = 1;
if($API_LastUpdateAnime->API_TheMovieRs->Status == "Not Complete"){ 
}else{
	$TotalSearchPage =$API_LastUpdateAnime->API_TheMovieRs->Body->TotalSearchPage;
}
// header('Content-type: application/xml; charset="ISO-8859-1"',true);  
?>
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>	
		<loc><?php echo base_url().'sitemap/anime/list-anime-0.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php foreach (range('A', 'Z') as $char) { ?>
	<sitemap>	
		<loc><?php echo base_url().'sitemap/anime/list-anime-'.$char.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php } ?>

<?php for($i = 1 ; $i <= $TotalSearchPage ;$i++) {?>
	<sitemap>	
		<loc><?php echo base_url().'sitemap/anime/anime-pages-'.$i.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php } ?>
</sitemapindex>

<!-- XML Sitemap generated by Yoast SEO -->
