
<?php 
header('Content-type: application/xml; charset="ISO-8859-1"',true);  
{// last update
  $TotalSearchPageHome = 0;
  if($API_LastUpdate->API_TheMovieRs->Status == "Not Complete"){ 
  }else{
    $TotalSearchPageHome = $API_LastUpdate->API_TheMovieRs->Body->TotalSearchPage;
  }
}
?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<?php for($i = 1 ; $i <= $TotalSearchPageHome ; $i++){ ?>
	<sitemap>	
		<loc><?php echo base_url().'web/sitemap-pages-'.$i.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
	<?php } ?>
  <sitemap>	
		<loc><?php echo base_url().'web/sitemap-menu.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
  </sitemap>
  
  <sitemap>	
      <loc><?php echo base_url().'web/sitemap-anime-0.xml';?></loc>
      <lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
  </sitemap>
  <?php foreach (range('A', 'Z') as $char) { ?>
    <sitemap>	
      <loc><?php echo base_url().'web/sitemap-anime-'.$char.'.xml';?></loc>
      <lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
    </sitemap>
  <?php } ?>
</sitemapindex>

<!-- XML Sitemap generated by Yoast SEO -->
