
<?php 
header('Content-type: application/xml; charset="ISO-8859-1"',true);  

?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<?php foreach($sitemapList as $sitemapListV){?>
	<sitemap>	
		<loc><?php echo base_url().'sitemap/'.$sitemapListV.'.xml';?></loc>
		<lastmod><?php echo date('Y-m-d\TH:i:s').'+00:00'?></lastmod>
	</sitemap>
<?php } ?>
</sitemapindex>

<!-- XML Sitemap generated by Yoast SEO -->
